export interface CompanyDetails {
  symbol: string
  assetType: string
  name: string
  description: string
  exchange: string
  currency: string
  country: string
  sector: string
  industry: string
  address: string
  officialSite: string
  fiscalYearEnd: string
  latestQuarter: string
  marketCapitalization: string
  bookValue: string
  dividendPerShare: string
  dividendYield: string
  revenuePerShareTTM: string
  profitMargin: string
  operatingMarginTTM: string
  returnOnAssetsTTM: string
  returnOnEquityTTM: string
  revenueTTM: string
  grossProfitTTM: string
  dilutedEPSTTM: string
  quarterlyEarningsGrowthYOY: string
  quarterlyRevenueGrowthYOY: string
  analystTargetPrice: string
  analystRatingStrongBuy: string
  analystRatingBuy: string
  analystRatingHold: string
  analystRatingSell: string
  analystRatingStrongSell: string
  trailingPE: string
  forwardPE: string
  priceToSalesRatioTTM: string
  priceToBookRatio: string
  beta: string
  _52WeekHigh: string
  _52WeekLow: string
  _50DayMovingAverage: string
  _200DayMovingAverage: string
  sharesOutstanding: string
  dividendDate: string
  exDividendDate: string
  cik: string
  peratio: string
  eps: string
  ebitda: string
  pegratio: string
  evtoEBITDA: string
  evtoRevenue: string
}
